### ISSUE TITLE
Error while using convert_vina_docked_pdbqt_to_pdbs.py

### ISSUE THREAD

**Issue by sathishdasari** [durrantlab/autogrow4#5]
When I tried the script to convert pdbqt to pdbs without any options it converted pdbqt.vina into individual pdb files. The following are the individual pdb files with binding free energies.

Gen_1_Cross_1507__1_pose_1.pdb:REMARK VINA RESULT:      -9.3      0.000      0.000
Gen_1_Cross_1507__1_pose_2.pdb:REMARK VINA RESULT:      -9.0      0.248      4.318
Gen_1_Cross_1507__1_pose_3.pdb:REMARK VINA RESULT:      -9.0      1.590      4.438
Gen_1_Cross_1507__1_pose_4.pdb:REMARK VINA RESULT:      -8.9      1.989      3.827
Gen_1_Cross_1507__1_pose_5.pdb:REMARK VINA RESULT:      -8.9      2.470      4.979
Gen_1_Cross_1507__1_pose_6.pdb:REMARK VINA RESULT:      -8.7      1.559      2.099
Gen_1_Cross_1507__1_pose_7.pdb:REMARK VINA RESULT:      -7.9      2.240      3.984
Gen_1_Cross_1507__1_pose_8.pdb:REMARK VINA RESULT:      -7.6      4.780      7.423
Gen_1_Cross_1507__1_pose_9.pdb:REMARK VINA RESULT:      -7.6      5.113      7.608

But when I tried using a --min_docking_score=-8.9 it gave me the following error.

Traceback (most recent call last):
  File "/home/s3dasari@NEXUS.UWATERLOO.CA/autogrow4/accessory_scripts/convert_vina_docked_pdbqt_to_pdbs.py", line 339, in <module>
    ARGS_DICT = get_arguments_from_argparse(ARGS_DICT)
  File "/home/s3dasari@NEXUS.UWATERLOO.CA/autogrow4/accessory_scripts/convert_vina_docked_pdbqt_to_pdbs.py", line 273, in get_arguments_from_argparse
    raise Exception("min_docking_score must be a float or None")
Exception: min_docking_score must be a float or None

**Comment by jaketanderson** [comment]
What happens if you add quotes? `--min_docking_score "-8.9"`
